(cl:defpackage bluerov2_control-srv
  (:use )
  (:export
   "CONVERTGEOPOINTS"
   "<CONVERTGEOPOINTS-REQUEST>"
   "CONVERTGEOPOINTS-REQUEST"
   "<CONVERTGEOPOINTS-RESPONSE>"
   "CONVERTGEOPOINTS-RESPONSE"
   "SETCONTROLMODE"
   "<SETCONTROLMODE-REQUEST>"
   "SETCONTROLMODE-REQUEST"
   "<SETCONTROLMODE-RESPONSE>"
   "SETCONTROLMODE-RESPONSE"
  ))

