// Generated by gencpp from file bluerov2_control/ConvertGeoPointsResponse.msg
// DO NOT EDIT!


#ifndef BLUEROV2_CONTROL_MESSAGE_CONVERTGEOPOINTSRESPONSE_H
#define BLUEROV2_CONTROL_MESSAGE_CONVERTGEOPOINTSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace bluerov2_control
{
template <class ContainerAllocator>
struct ConvertGeoPointsResponse_
{
  typedef ConvertGeoPointsResponse_<ContainerAllocator> Type;

  ConvertGeoPointsResponse_()
    : utmpoints()  {
    }
  ConvertGeoPointsResponse_(const ContainerAllocator& _alloc)
    : utmpoints(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point_<ContainerAllocator> >> _utmpoints_type;
  _utmpoints_type utmpoints;





  typedef boost::shared_ptr< ::bluerov2_control::ConvertGeoPointsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bluerov2_control::ConvertGeoPointsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ConvertGeoPointsResponse_

typedef ::bluerov2_control::ConvertGeoPointsResponse_<std::allocator<void> > ConvertGeoPointsResponse;

typedef boost::shared_ptr< ::bluerov2_control::ConvertGeoPointsResponse > ConvertGeoPointsResponsePtr;
typedef boost::shared_ptr< ::bluerov2_control::ConvertGeoPointsResponse const> ConvertGeoPointsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bluerov2_control::ConvertGeoPointsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bluerov2_control::ConvertGeoPointsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bluerov2_control::ConvertGeoPointsResponse_<ContainerAllocator1> & lhs, const ::bluerov2_control::ConvertGeoPointsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.utmpoints == rhs.utmpoints;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bluerov2_control::ConvertGeoPointsResponse_<ContainerAllocator1> & lhs, const ::bluerov2_control::ConvertGeoPointsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bluerov2_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::bluerov2_control::ConvertGeoPointsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bluerov2_control::ConvertGeoPointsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bluerov2_control::ConvertGeoPointsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bluerov2_control::ConvertGeoPointsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bluerov2_control::ConvertGeoPointsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bluerov2_control::ConvertGeoPointsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bluerov2_control::ConvertGeoPointsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "99c794da9bcae9f599e7efd1c9cf51d7";
  }

  static const char* value(const ::bluerov2_control::ConvertGeoPointsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x99c794da9bcae9f5ULL;
  static const uint64_t static_value2 = 0x99e7efd1c9cf51d7ULL;
};

template<class ContainerAllocator>
struct DataType< ::bluerov2_control::ConvertGeoPointsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bluerov2_control/ConvertGeoPointsResponse";
  }

  static const char* value(const ::bluerov2_control::ConvertGeoPointsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bluerov2_control::ConvertGeoPointsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point[] utmpoints\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::bluerov2_control::ConvertGeoPointsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bluerov2_control::ConvertGeoPointsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.utmpoints);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ConvertGeoPointsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bluerov2_control::ConvertGeoPointsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bluerov2_control::ConvertGeoPointsResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "utmpoints: ";
    if (v.utmpoints.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.utmpoints.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.utmpoints[i]);
    }
    if (v.utmpoints.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // BLUEROV2_CONTROL_MESSAGE_CONVERTGEOPOINTSRESPONSE_H
