// Generated by gencpp from file bluerov2_control/ConvertGeoPointsRequest.msg
// DO NOT EDIT!


#ifndef BLUEROV2_CONTROL_MESSAGE_CONVERTGEOPOINTSREQUEST_H
#define BLUEROV2_CONTROL_MESSAGE_CONVERTGEOPOINTSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geographic_msgs/GeoPoint.h>

namespace bluerov2_control
{
template <class ContainerAllocator>
struct ConvertGeoPointsRequest_
{
  typedef ConvertGeoPointsRequest_<ContainerAllocator> Type;

  ConvertGeoPointsRequest_()
    : geopoints()  {
    }
  ConvertGeoPointsRequest_(const ContainerAllocator& _alloc)
    : geopoints(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geographic_msgs::GeoPoint_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geographic_msgs::GeoPoint_<ContainerAllocator> >> _geopoints_type;
  _geopoints_type geopoints;





  typedef boost::shared_ptr< ::bluerov2_control::ConvertGeoPointsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bluerov2_control::ConvertGeoPointsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ConvertGeoPointsRequest_

typedef ::bluerov2_control::ConvertGeoPointsRequest_<std::allocator<void> > ConvertGeoPointsRequest;

typedef boost::shared_ptr< ::bluerov2_control::ConvertGeoPointsRequest > ConvertGeoPointsRequestPtr;
typedef boost::shared_ptr< ::bluerov2_control::ConvertGeoPointsRequest const> ConvertGeoPointsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bluerov2_control::ConvertGeoPointsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bluerov2_control::ConvertGeoPointsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bluerov2_control::ConvertGeoPointsRequest_<ContainerAllocator1> & lhs, const ::bluerov2_control::ConvertGeoPointsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.geopoints == rhs.geopoints;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bluerov2_control::ConvertGeoPointsRequest_<ContainerAllocator1> & lhs, const ::bluerov2_control::ConvertGeoPointsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bluerov2_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::bluerov2_control::ConvertGeoPointsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bluerov2_control::ConvertGeoPointsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bluerov2_control::ConvertGeoPointsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bluerov2_control::ConvertGeoPointsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bluerov2_control::ConvertGeoPointsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bluerov2_control::ConvertGeoPointsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bluerov2_control::ConvertGeoPointsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8bbeac8c86c7cfa3d22cd50dc8855fa5";
  }

  static const char* value(const ::bluerov2_control::ConvertGeoPointsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8bbeac8c86c7cfa3ULL;
  static const uint64_t static_value2 = 0xd22cd50dc8855fa5ULL;
};

template<class ContainerAllocator>
struct DataType< ::bluerov2_control::ConvertGeoPointsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bluerov2_control/ConvertGeoPointsRequest";
  }

  static const char* value(const ::bluerov2_control::ConvertGeoPointsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bluerov2_control::ConvertGeoPointsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geographic_msgs/GeoPoint[] geopoints\n"
"\n"
"================================================================================\n"
"MSG: geographic_msgs/GeoPoint\n"
"# Geographic point, using the WGS 84 reference ellipsoid.\n"
"\n"
"# Latitude [degrees]. Positive is north of equator; negative is south\n"
"# (-90 <= latitude <= +90).\n"
"float64 latitude\n"
"\n"
"# Longitude [degrees]. Positive is east of prime meridian; negative is\n"
"# west (-180 <= longitude <= +180). At the poles, latitude is -90 or\n"
"# +90, and longitude is irrelevant, but must be in range.\n"
"float64 longitude\n"
"\n"
"# Altitude [m]. Positive is above the WGS 84 ellipsoid (NaN if unspecified).\n"
"float64 altitude\n"
;
  }

  static const char* value(const ::bluerov2_control::ConvertGeoPointsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bluerov2_control::ConvertGeoPointsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.geopoints);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ConvertGeoPointsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bluerov2_control::ConvertGeoPointsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bluerov2_control::ConvertGeoPointsRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "geopoints: ";
    if (v.geopoints.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.geopoints.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::geographic_msgs::GeoPoint_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.geopoints[i]);
    }
    if (v.geopoints.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // BLUEROV2_CONTROL_MESSAGE_CONVERTGEOPOINTSREQUEST_H
