// Generated by gencpp from file bluerov2_control/FollowWaypointsAction.msg
// DO NOT EDIT!


#ifndef BLUEROV2_CONTROL_MESSAGE_FOLLOWWAYPOINTSACTION_H
#define BLUEROV2_CONTROL_MESSAGE_FOLLOWWAYPOINTSACTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <bluerov2_control/FollowWaypointsActionGoal.h>
#include <bluerov2_control/FollowWaypointsActionResult.h>
#include <bluerov2_control/FollowWaypointsActionFeedback.h>

namespace bluerov2_control
{
template <class ContainerAllocator>
struct FollowWaypointsAction_
{
  typedef FollowWaypointsAction_<ContainerAllocator> Type;

  FollowWaypointsAction_()
    : action_goal()
    , action_result()
    , action_feedback()  {
    }
  FollowWaypointsAction_(const ContainerAllocator& _alloc)
    : action_goal(_alloc)
    , action_result(_alloc)
    , action_feedback(_alloc)  {
  (void)_alloc;
    }



   typedef  ::bluerov2_control::FollowWaypointsActionGoal_<ContainerAllocator>  _action_goal_type;
  _action_goal_type action_goal;

   typedef  ::bluerov2_control::FollowWaypointsActionResult_<ContainerAllocator>  _action_result_type;
  _action_result_type action_result;

   typedef  ::bluerov2_control::FollowWaypointsActionFeedback_<ContainerAllocator>  _action_feedback_type;
  _action_feedback_type action_feedback;





  typedef boost::shared_ptr< ::bluerov2_control::FollowWaypointsAction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bluerov2_control::FollowWaypointsAction_<ContainerAllocator> const> ConstPtr;

}; // struct FollowWaypointsAction_

typedef ::bluerov2_control::FollowWaypointsAction_<std::allocator<void> > FollowWaypointsAction;

typedef boost::shared_ptr< ::bluerov2_control::FollowWaypointsAction > FollowWaypointsActionPtr;
typedef boost::shared_ptr< ::bluerov2_control::FollowWaypointsAction const> FollowWaypointsActionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bluerov2_control::FollowWaypointsAction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bluerov2_control::FollowWaypointsAction_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bluerov2_control::FollowWaypointsAction_<ContainerAllocator1> & lhs, const ::bluerov2_control::FollowWaypointsAction_<ContainerAllocator2> & rhs)
{
  return lhs.action_goal == rhs.action_goal &&
    lhs.action_result == rhs.action_result &&
    lhs.action_feedback == rhs.action_feedback;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bluerov2_control::FollowWaypointsAction_<ContainerAllocator1> & lhs, const ::bluerov2_control::FollowWaypointsAction_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bluerov2_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::bluerov2_control::FollowWaypointsAction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bluerov2_control::FollowWaypointsAction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bluerov2_control::FollowWaypointsAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bluerov2_control::FollowWaypointsAction_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bluerov2_control::FollowWaypointsAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bluerov2_control::FollowWaypointsAction_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bluerov2_control::FollowWaypointsAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3cfe385f9cb10ff7e7be6215f7fbd383";
  }

  static const char* value(const ::bluerov2_control::FollowWaypointsAction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3cfe385f9cb10ff7ULL;
  static const uint64_t static_value2 = 0xe7be6215f7fbd383ULL;
};

template<class ContainerAllocator>
struct DataType< ::bluerov2_control::FollowWaypointsAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bluerov2_control/FollowWaypointsAction";
  }

  static const char* value(const ::bluerov2_control::FollowWaypointsAction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bluerov2_control::FollowWaypointsAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"FollowWaypointsActionGoal action_goal\n"
"FollowWaypointsActionResult action_result\n"
"FollowWaypointsActionFeedback action_feedback\n"
"\n"
"================================================================================\n"
"MSG: bluerov2_control/FollowWaypointsActionGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"FollowWaypointsGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: bluerov2_control/FollowWaypointsGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define the goal\n"
"uuv_control_msgs/WaypointSet waypoints\n"
"\n"
"================================================================================\n"
"MSG: uuv_control_msgs/WaypointSet\n"
"# Copyright (c) 2016 The UUV Simulator Authors.\n"
"# All rights reserved.\n"
"#\n"
"# Licensed under the Apache License, Version 2.0 (the \"License\");\n"
"# you may not use this file except in compliance with the License.\n"
"# You may obtain a copy of the License at\n"
"#\n"
"#     http://www.apache.org/licenses/LICENSE-2.0\n"
"#\n"
"# Unless required by applicable law or agreed to in writing, software\n"
"# distributed under the License is distributed on an \"AS IS\" BASIS,\n"
"# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
"# See the License for the specific language governing permissions and\n"
"# limitations under the License.\n"
"\n"
"std_msgs/Header header\n"
"std_msgs/Time start_time\n"
"uuv_control_msgs/Waypoint[] waypoints\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Time\n"
"time data\n"
"\n"
"================================================================================\n"
"MSG: uuv_control_msgs/Waypoint\n"
"# Copyright (c) 2016 The UUV Simulator Authors.\n"
"# All rights reserved.\n"
"#\n"
"# Licensed under the Apache License, Version 2.0 (the \"License\");\n"
"# you may not use this file except in compliance with the License.\n"
"# You may obtain a copy of the License at\n"
"#\n"
"#     http://www.apache.org/licenses/LICENSE-2.0\n"
"#\n"
"# Unless required by applicable law or agreed to in writing, software\n"
"# distributed under the License is distributed on an \"AS IS\" BASIS,\n"
"# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
"# See the License for the specific language governing permissions and\n"
"# limitations under the License.\n"
"\n"
"std_msgs/Header header\n"
"geometry_msgs/Point point\n"
"float64 max_forward_speed\n"
"float64 heading_offset\n"
"bool use_fixed_heading\n"
"float64 radius_of_acceptance\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: bluerov2_control/FollowWaypointsActionResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"FollowWaypointsResult result\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalStatus\n"
"GoalID goal_id\n"
"uint8 status\n"
"uint8 PENDING         = 0   # The goal has yet to be processed by the action server\n"
"uint8 ACTIVE          = 1   # The goal is currently being processed by the action server\n"
"uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing\n"
"                            #   and has since completed its execution (Terminal State)\n"
"uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)\n"
"uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due\n"
"                            #    to some failure (Terminal State)\n"
"uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,\n"
"                            #    because the goal was unattainable or invalid (Terminal State)\n"
"uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing\n"
"                            #    and has not yet completed execution\n"
"uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,\n"
"                            #    but the action server has not yet confirmed that the goal is canceled\n"
"uint8 RECALLED        = 8   # The goal received a cancel request before it started executing\n"
"                            #    and was successfully cancelled (Terminal State)\n"
"uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be\n"
"                            #    sent over the wire by an action server\n"
"\n"
"#Allow for the user to associate a string with GoalStatus for debugging\n"
"string text\n"
"\n"
"\n"
"================================================================================\n"
"MSG: bluerov2_control/FollowWaypointsResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define the result\n"
"uint32 waypoints_completed\n"
"\n"
"================================================================================\n"
"MSG: bluerov2_control/FollowWaypointsActionFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"FollowWaypointsFeedback feedback\n"
"\n"
"================================================================================\n"
"MSG: bluerov2_control/FollowWaypointsFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define a feedback message\n"
"float32 percentage_complete\n"
;
  }

  static const char* value(const ::bluerov2_control::FollowWaypointsAction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bluerov2_control::FollowWaypointsAction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action_goal);
      stream.next(m.action_result);
      stream.next(m.action_feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FollowWaypointsAction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bluerov2_control::FollowWaypointsAction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bluerov2_control::FollowWaypointsAction_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "action_goal: ";
    Printer< ::bluerov2_control::FollowWaypointsActionGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.action_goal);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "action_result: ";
    Printer< ::bluerov2_control::FollowWaypointsActionResult_<ContainerAllocator> >::stream(s, indent + "  ", v.action_result);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "action_feedback: ";
    Printer< ::bluerov2_control::FollowWaypointsActionFeedback_<ContainerAllocator> >::stream(s, indent + "  ", v.action_feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BLUEROV2_CONTROL_MESSAGE_FOLLOWWAYPOINTSACTION_H
