// Generated by gencpp from file bluerov2_control/FollowWaypointsGoal.msg
// DO NOT EDIT!


#ifndef BLUEROV2_CONTROL_MESSAGE_FOLLOWWAYPOINTSGOAL_H
#define BLUEROV2_CONTROL_MESSAGE_FOLLOWWAYPOINTSGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <uuv_control_msgs/WaypointSet.h>

namespace bluerov2_control
{
template <class ContainerAllocator>
struct FollowWaypointsGoal_
{
  typedef FollowWaypointsGoal_<ContainerAllocator> Type;

  FollowWaypointsGoal_()
    : waypoints()  {
    }
  FollowWaypointsGoal_(const ContainerAllocator& _alloc)
    : waypoints(_alloc)  {
  (void)_alloc;
    }



   typedef  ::uuv_control_msgs::WaypointSet_<ContainerAllocator>  _waypoints_type;
  _waypoints_type waypoints;





  typedef boost::shared_ptr< ::bluerov2_control::FollowWaypointsGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bluerov2_control::FollowWaypointsGoal_<ContainerAllocator> const> ConstPtr;

}; // struct FollowWaypointsGoal_

typedef ::bluerov2_control::FollowWaypointsGoal_<std::allocator<void> > FollowWaypointsGoal;

typedef boost::shared_ptr< ::bluerov2_control::FollowWaypointsGoal > FollowWaypointsGoalPtr;
typedef boost::shared_ptr< ::bluerov2_control::FollowWaypointsGoal const> FollowWaypointsGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bluerov2_control::FollowWaypointsGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bluerov2_control::FollowWaypointsGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bluerov2_control::FollowWaypointsGoal_<ContainerAllocator1> & lhs, const ::bluerov2_control::FollowWaypointsGoal_<ContainerAllocator2> & rhs)
{
  return lhs.waypoints == rhs.waypoints;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bluerov2_control::FollowWaypointsGoal_<ContainerAllocator1> & lhs, const ::bluerov2_control::FollowWaypointsGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bluerov2_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::bluerov2_control::FollowWaypointsGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bluerov2_control::FollowWaypointsGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bluerov2_control::FollowWaypointsGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bluerov2_control::FollowWaypointsGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bluerov2_control::FollowWaypointsGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bluerov2_control::FollowWaypointsGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bluerov2_control::FollowWaypointsGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "58e5d76705941fad7db4292f7d5be15d";
  }

  static const char* value(const ::bluerov2_control::FollowWaypointsGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x58e5d76705941fadULL;
  static const uint64_t static_value2 = 0x7db4292f7d5be15dULL;
};

template<class ContainerAllocator>
struct DataType< ::bluerov2_control::FollowWaypointsGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bluerov2_control/FollowWaypointsGoal";
  }

  static const char* value(const ::bluerov2_control::FollowWaypointsGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bluerov2_control::FollowWaypointsGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define the goal\n"
"uuv_control_msgs/WaypointSet waypoints\n"
"\n"
"================================================================================\n"
"MSG: uuv_control_msgs/WaypointSet\n"
"# Copyright (c) 2016 The UUV Simulator Authors.\n"
"# All rights reserved.\n"
"#\n"
"# Licensed under the Apache License, Version 2.0 (the \"License\");\n"
"# you may not use this file except in compliance with the License.\n"
"# You may obtain a copy of the License at\n"
"#\n"
"#     http://www.apache.org/licenses/LICENSE-2.0\n"
"#\n"
"# Unless required by applicable law or agreed to in writing, software\n"
"# distributed under the License is distributed on an \"AS IS\" BASIS,\n"
"# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
"# See the License for the specific language governing permissions and\n"
"# limitations under the License.\n"
"\n"
"std_msgs/Header header\n"
"std_msgs/Time start_time\n"
"uuv_control_msgs/Waypoint[] waypoints\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Time\n"
"time data\n"
"\n"
"================================================================================\n"
"MSG: uuv_control_msgs/Waypoint\n"
"# Copyright (c) 2016 The UUV Simulator Authors.\n"
"# All rights reserved.\n"
"#\n"
"# Licensed under the Apache License, Version 2.0 (the \"License\");\n"
"# you may not use this file except in compliance with the License.\n"
"# You may obtain a copy of the License at\n"
"#\n"
"#     http://www.apache.org/licenses/LICENSE-2.0\n"
"#\n"
"# Unless required by applicable law or agreed to in writing, software\n"
"# distributed under the License is distributed on an \"AS IS\" BASIS,\n"
"# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
"# See the License for the specific language governing permissions and\n"
"# limitations under the License.\n"
"\n"
"std_msgs/Header header\n"
"geometry_msgs/Point point\n"
"float64 max_forward_speed\n"
"float64 heading_offset\n"
"bool use_fixed_heading\n"
"float64 radius_of_acceptance\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::bluerov2_control::FollowWaypointsGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bluerov2_control::FollowWaypointsGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.waypoints);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FollowWaypointsGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bluerov2_control::FollowWaypointsGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bluerov2_control::FollowWaypointsGoal_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "waypoints: ";
    Printer< ::uuv_control_msgs::WaypointSet_<ContainerAllocator> >::stream(s, indent + "  ", v.waypoints);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BLUEROV2_CONTROL_MESSAGE_FOLLOWWAYPOINTSGOAL_H
