// Generated by gencpp from file bluerov2_control/FollowWaypointsFeedback.msg
// DO NOT EDIT!


#ifndef BLUEROV2_CONTROL_MESSAGE_FOLLOWWAYPOINTSFEEDBACK_H
#define BLUEROV2_CONTROL_MESSAGE_FOLLOWWAYPOINTSFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace bluerov2_control
{
template <class ContainerAllocator>
struct FollowWaypointsFeedback_
{
  typedef FollowWaypointsFeedback_<ContainerAllocator> Type;

  FollowWaypointsFeedback_()
    : percentage_complete(0.0)  {
    }
  FollowWaypointsFeedback_(const ContainerAllocator& _alloc)
    : percentage_complete(0.0)  {
  (void)_alloc;
    }



   typedef float _percentage_complete_type;
  _percentage_complete_type percentage_complete;





  typedef boost::shared_ptr< ::bluerov2_control::FollowWaypointsFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bluerov2_control::FollowWaypointsFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct FollowWaypointsFeedback_

typedef ::bluerov2_control::FollowWaypointsFeedback_<std::allocator<void> > FollowWaypointsFeedback;

typedef boost::shared_ptr< ::bluerov2_control::FollowWaypointsFeedback > FollowWaypointsFeedbackPtr;
typedef boost::shared_ptr< ::bluerov2_control::FollowWaypointsFeedback const> FollowWaypointsFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bluerov2_control::FollowWaypointsFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bluerov2_control::FollowWaypointsFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bluerov2_control::FollowWaypointsFeedback_<ContainerAllocator1> & lhs, const ::bluerov2_control::FollowWaypointsFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.percentage_complete == rhs.percentage_complete;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bluerov2_control::FollowWaypointsFeedback_<ContainerAllocator1> & lhs, const ::bluerov2_control::FollowWaypointsFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bluerov2_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::bluerov2_control::FollowWaypointsFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bluerov2_control::FollowWaypointsFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bluerov2_control::FollowWaypointsFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bluerov2_control::FollowWaypointsFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bluerov2_control::FollowWaypointsFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bluerov2_control::FollowWaypointsFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bluerov2_control::FollowWaypointsFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e59a2842413d60206f458c042f7cfd36";
  }

  static const char* value(const ::bluerov2_control::FollowWaypointsFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe59a2842413d6020ULL;
  static const uint64_t static_value2 = 0x6f458c042f7cfd36ULL;
};

template<class ContainerAllocator>
struct DataType< ::bluerov2_control::FollowWaypointsFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bluerov2_control/FollowWaypointsFeedback";
  }

  static const char* value(const ::bluerov2_control::FollowWaypointsFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bluerov2_control::FollowWaypointsFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define a feedback message\n"
"float32 percentage_complete\n"
;
  }

  static const char* value(const ::bluerov2_control::FollowWaypointsFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bluerov2_control::FollowWaypointsFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.percentage_complete);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FollowWaypointsFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bluerov2_control::FollowWaypointsFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bluerov2_control::FollowWaypointsFeedback_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "percentage_complete: ";
    Printer<float>::stream(s, indent + "  ", v.percentage_complete);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BLUEROV2_CONTROL_MESSAGE_FOLLOWWAYPOINTSFEEDBACK_H
