// Generated by gencpp from file bluerov2_control/FollowWaypointsResult.msg
// DO NOT EDIT!


#ifndef BLUEROV2_CONTROL_MESSAGE_FOLLOWWAYPOINTSRESULT_H
#define BLUEROV2_CONTROL_MESSAGE_FOLLOWWAYPOINTSRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace bluerov2_control
{
template <class ContainerAllocator>
struct FollowWaypointsResult_
{
  typedef FollowWaypointsResult_<ContainerAllocator> Type;

  FollowWaypointsResult_()
    : waypoints_completed(0)  {
    }
  FollowWaypointsResult_(const ContainerAllocator& _alloc)
    : waypoints_completed(0)  {
  (void)_alloc;
    }



   typedef uint32_t _waypoints_completed_type;
  _waypoints_completed_type waypoints_completed;





  typedef boost::shared_ptr< ::bluerov2_control::FollowWaypointsResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bluerov2_control::FollowWaypointsResult_<ContainerAllocator> const> ConstPtr;

}; // struct FollowWaypointsResult_

typedef ::bluerov2_control::FollowWaypointsResult_<std::allocator<void> > FollowWaypointsResult;

typedef boost::shared_ptr< ::bluerov2_control::FollowWaypointsResult > FollowWaypointsResultPtr;
typedef boost::shared_ptr< ::bluerov2_control::FollowWaypointsResult const> FollowWaypointsResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bluerov2_control::FollowWaypointsResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bluerov2_control::FollowWaypointsResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bluerov2_control::FollowWaypointsResult_<ContainerAllocator1> & lhs, const ::bluerov2_control::FollowWaypointsResult_<ContainerAllocator2> & rhs)
{
  return lhs.waypoints_completed == rhs.waypoints_completed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bluerov2_control::FollowWaypointsResult_<ContainerAllocator1> & lhs, const ::bluerov2_control::FollowWaypointsResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bluerov2_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::bluerov2_control::FollowWaypointsResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bluerov2_control::FollowWaypointsResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bluerov2_control::FollowWaypointsResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bluerov2_control::FollowWaypointsResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bluerov2_control::FollowWaypointsResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bluerov2_control::FollowWaypointsResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bluerov2_control::FollowWaypointsResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a91b58e3838e0eae5c75dc8d25cfb82";
  }

  static const char* value(const ::bluerov2_control::FollowWaypointsResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a91b58e3838e0eaULL;
  static const uint64_t static_value2 = 0xe5c75dc8d25cfb82ULL;
};

template<class ContainerAllocator>
struct DataType< ::bluerov2_control::FollowWaypointsResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bluerov2_control/FollowWaypointsResult";
  }

  static const char* value(const ::bluerov2_control::FollowWaypointsResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bluerov2_control::FollowWaypointsResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define the result\n"
"uint32 waypoints_completed\n"
;
  }

  static const char* value(const ::bluerov2_control::FollowWaypointsResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bluerov2_control::FollowWaypointsResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.waypoints_completed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FollowWaypointsResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bluerov2_control::FollowWaypointsResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bluerov2_control::FollowWaypointsResult_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "waypoints_completed: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.waypoints_completed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BLUEROV2_CONTROL_MESSAGE_FOLLOWWAYPOINTSRESULT_H
