//#line 2 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the bluerov2_control package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __bluerov2_control__PID_RECONFIGCONFIG_H__
#define __bluerov2_control__PID_RECONFIGCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace bluerov2_control
{
  class pid_reconfigConfigStatics;

  class pid_reconfigConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      virtual ~AbstractParamDescription() = default;

      virtual void clamp(pid_reconfigConfig &config, const pid_reconfigConfig &max, const pid_reconfigConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const pid_reconfigConfig &config1, const pid_reconfigConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, pid_reconfigConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const pid_reconfigConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, pid_reconfigConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const pid_reconfigConfig &config) const = 0;
      virtual void getValue(const pid_reconfigConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T pid_reconfigConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T pid_reconfigConfig::* field;

      virtual void clamp(pid_reconfigConfig &config, const pid_reconfigConfig &max, const pid_reconfigConfig &min) const override
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const pid_reconfigConfig &config1, const pid_reconfigConfig &config2) const override
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, pid_reconfigConfig &config) const override
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const pid_reconfigConfig &config) const override
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, pid_reconfigConfig &config) const override
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const pid_reconfigConfig &config) const override
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const pid_reconfigConfig &config, boost::any &val) const override
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      virtual ~AbstractGroupDescription() = default;

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, pid_reconfigConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, pid_reconfigConfig &top) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const override
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<pid_reconfigConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(pid_reconfigConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("accel_x_kp"==(*_i)->name){accel_x_kp = boost::any_cast<double>(val);}
        if("accel_x_ki"==(*_i)->name){accel_x_ki = boost::any_cast<double>(val);}
        if("accel_x_kd"==(*_i)->name){accel_x_kd = boost::any_cast<double>(val);}
        if("accel_x_sat"==(*_i)->name){accel_x_sat = boost::any_cast<double>(val);}
        if("accel_y_kp"==(*_i)->name){accel_y_kp = boost::any_cast<double>(val);}
        if("accel_y_ki"==(*_i)->name){accel_y_ki = boost::any_cast<double>(val);}
        if("accel_y_kd"==(*_i)->name){accel_y_kd = boost::any_cast<double>(val);}
        if("accel_y_sat"==(*_i)->name){accel_y_sat = boost::any_cast<double>(val);}
        if("accel_z_kp"==(*_i)->name){accel_z_kp = boost::any_cast<double>(val);}
        if("accel_z_ki"==(*_i)->name){accel_z_ki = boost::any_cast<double>(val);}
        if("accel_z_kd"==(*_i)->name){accel_z_kd = boost::any_cast<double>(val);}
        if("accel_z_sat"==(*_i)->name){accel_z_sat = boost::any_cast<double>(val);}
        if("accel_r_kp"==(*_i)->name){accel_r_kp = boost::any_cast<double>(val);}
        if("accel_r_ki"==(*_i)->name){accel_r_ki = boost::any_cast<double>(val);}
        if("accel_r_kd"==(*_i)->name){accel_r_kd = boost::any_cast<double>(val);}
        if("accel_r_sat"==(*_i)->name){accel_r_sat = boost::any_cast<double>(val);}
        if("vel_x_kp"==(*_i)->name){vel_x_kp = boost::any_cast<double>(val);}
        if("vel_x_ki"==(*_i)->name){vel_x_ki = boost::any_cast<double>(val);}
        if("vel_x_kd"==(*_i)->name){vel_x_kd = boost::any_cast<double>(val);}
        if("vel_x_sat"==(*_i)->name){vel_x_sat = boost::any_cast<double>(val);}
        if("vel_x_lim"==(*_i)->name){vel_x_lim = boost::any_cast<double>(val);}
        if("vel_y_kp"==(*_i)->name){vel_y_kp = boost::any_cast<double>(val);}
        if("vel_y_ki"==(*_i)->name){vel_y_ki = boost::any_cast<double>(val);}
        if("vel_y_kd"==(*_i)->name){vel_y_kd = boost::any_cast<double>(val);}
        if("vel_y_sat"==(*_i)->name){vel_y_sat = boost::any_cast<double>(val);}
        if("vel_y_lim"==(*_i)->name){vel_y_lim = boost::any_cast<double>(val);}
        if("vel_z_kp"==(*_i)->name){vel_z_kp = boost::any_cast<double>(val);}
        if("vel_z_ki"==(*_i)->name){vel_z_ki = boost::any_cast<double>(val);}
        if("vel_z_kd"==(*_i)->name){vel_z_kd = boost::any_cast<double>(val);}
        if("vel_z_sat"==(*_i)->name){vel_z_sat = boost::any_cast<double>(val);}
        if("vel_z_lim"==(*_i)->name){vel_z_lim = boost::any_cast<double>(val);}
        if("vel_r_kp"==(*_i)->name){vel_r_kp = boost::any_cast<double>(val);}
        if("vel_r_ki"==(*_i)->name){vel_r_ki = boost::any_cast<double>(val);}
        if("vel_r_kd"==(*_i)->name){vel_r_kd = boost::any_cast<double>(val);}
        if("vel_r_sat"==(*_i)->name){vel_r_sat = boost::any_cast<double>(val);}
        if("vel_r_lim"==(*_i)->name){vel_r_lim = boost::any_cast<double>(val);}
        if("pos_x_kp"==(*_i)->name){pos_x_kp = boost::any_cast<double>(val);}
        if("pos_x_ki"==(*_i)->name){pos_x_ki = boost::any_cast<double>(val);}
        if("pos_x_kd"==(*_i)->name){pos_x_kd = boost::any_cast<double>(val);}
        if("pos_x_sat"==(*_i)->name){pos_x_sat = boost::any_cast<double>(val);}
        if("pos_y_kp"==(*_i)->name){pos_y_kp = boost::any_cast<double>(val);}
        if("pos_y_ki"==(*_i)->name){pos_y_ki = boost::any_cast<double>(val);}
        if("pos_y_kd"==(*_i)->name){pos_y_kd = boost::any_cast<double>(val);}
        if("pos_y_sat"==(*_i)->name){pos_y_sat = boost::any_cast<double>(val);}
        if("pos_z_kp"==(*_i)->name){pos_z_kp = boost::any_cast<double>(val);}
        if("pos_z_ki"==(*_i)->name){pos_z_ki = boost::any_cast<double>(val);}
        if("pos_z_kd"==(*_i)->name){pos_z_kd = boost::any_cast<double>(val);}
        if("pos_z_sat"==(*_i)->name){pos_z_sat = boost::any_cast<double>(val);}
        if("pos_r_kp"==(*_i)->name){pos_r_kp = boost::any_cast<double>(val);}
        if("pos_r_ki"==(*_i)->name){pos_r_ki = boost::any_cast<double>(val);}
        if("pos_r_kd"==(*_i)->name){pos_r_kd = boost::any_cast<double>(val);}
        if("pos_r_sat"==(*_i)->name){pos_r_sat = boost::any_cast<double>(val);}
      }
    }

    double accel_x_kp;
double accel_x_ki;
double accel_x_kd;
double accel_x_sat;
double accel_y_kp;
double accel_y_ki;
double accel_y_kd;
double accel_y_sat;
double accel_z_kp;
double accel_z_ki;
double accel_z_kd;
double accel_z_sat;
double accel_r_kp;
double accel_r_ki;
double accel_r_kd;
double accel_r_sat;
double vel_x_kp;
double vel_x_ki;
double vel_x_kd;
double vel_x_sat;
double vel_x_lim;
double vel_y_kp;
double vel_y_ki;
double vel_y_kd;
double vel_y_sat;
double vel_y_lim;
double vel_z_kp;
double vel_z_ki;
double vel_z_kd;
double vel_z_sat;
double vel_z_lim;
double vel_r_kp;
double vel_r_ki;
double vel_r_kd;
double vel_r_sat;
double vel_r_lim;
double pos_x_kp;
double pos_x_ki;
double pos_x_kd;
double pos_x_sat;
double pos_y_kp;
double pos_y_ki;
double pos_y_kd;
double pos_y_sat;
double pos_z_kp;
double pos_z_ki;
double pos_z_kd;
double pos_z_sat;
double pos_r_kp;
double pos_r_ki;
double pos_r_kd;
double pos_r_sat;

    bool state;
    std::string name;

    
}groups;



//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double accel_x_kp;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double accel_x_ki;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double accel_x_kd;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double accel_x_sat;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double accel_y_kp;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double accel_y_ki;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double accel_y_kd;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double accel_y_sat;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double accel_z_kp;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double accel_z_ki;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double accel_z_kd;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double accel_z_sat;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double accel_r_kp;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double accel_r_ki;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double accel_r_kd;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double accel_r_sat;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double vel_x_kp;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double vel_x_ki;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double vel_x_kd;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double vel_x_sat;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double vel_x_lim;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double vel_y_kp;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double vel_y_ki;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double vel_y_kd;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double vel_y_sat;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double vel_y_lim;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double vel_z_kp;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double vel_z_ki;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double vel_z_kd;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double vel_z_sat;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double vel_z_lim;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double vel_r_kp;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double vel_r_ki;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double vel_r_kd;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double vel_r_sat;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double vel_r_lim;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double pos_x_kp;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double pos_x_ki;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double pos_x_kd;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double pos_x_sat;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double pos_y_kp;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double pos_y_ki;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double pos_y_kd;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double pos_y_sat;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double pos_z_kp;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double pos_z_ki;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double pos_z_kd;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double pos_z_sat;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double pos_r_kp;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double pos_r_ki;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double pos_r_kd;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double pos_r_sat;
//#line 231 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("pid_reconfigConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (size_t i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (size_t i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (size_t i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (size_t i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const pid_reconfigConfig &__max__ = __getMax__();
      const pid_reconfigConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const pid_reconfigConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const pid_reconfigConfig &__getDefault__();
    static const pid_reconfigConfig &__getMax__();
    static const pid_reconfigConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const pid_reconfigConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void pid_reconfigConfig::ParamDescription<std::string>::clamp(pid_reconfigConfig &config, const pid_reconfigConfig &max, const pid_reconfigConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class pid_reconfigConfigStatics
  {
    friend class pid_reconfigConfig;

    pid_reconfigConfigStatics()
    {
pid_reconfigConfig::GroupDescription<pid_reconfigConfig::DEFAULT, pid_reconfigConfig> Default("Default", "", 0, 0, true, &pid_reconfigConfig::groups);
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.accel_x_kp = -400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.accel_x_kp = 400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.accel_x_kp = 1.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("accel_x_kp", "double", 0, "kp x Gain Acceleration", "", &pid_reconfigConfig::accel_x_kp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("accel_x_kp", "double", 0, "kp x Gain Acceleration", "", &pid_reconfigConfig::accel_x_kp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.accel_x_ki = -400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.accel_x_ki = 400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.accel_x_ki = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("accel_x_ki", "double", 0, "ki x Gain Acceleration", "", &pid_reconfigConfig::accel_x_ki)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("accel_x_ki", "double", 0, "ki x Gain Acceleration", "", &pid_reconfigConfig::accel_x_ki)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.accel_x_kd = -400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.accel_x_kd = 400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.accel_x_kd = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("accel_x_kd", "double", 0, "kd x Gain Acceleration", "", &pid_reconfigConfig::accel_x_kd)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("accel_x_kd", "double", 0, "kd x Gain Acceleration", "", &pid_reconfigConfig::accel_x_kd)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.accel_x_sat = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.accel_x_sat = 110.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.accel_x_sat = 1.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("accel_x_sat", "double", 0, "Surge Force Saturation (N)", "", &pid_reconfigConfig::accel_x_sat)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("accel_x_sat", "double", 0, "Surge Force Saturation (N)", "", &pid_reconfigConfig::accel_x_sat)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.accel_y_kp = -400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.accel_y_kp = 400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.accel_y_kp = 1.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("accel_y_kp", "double", 0, "kp y Gain Acceleration", "", &pid_reconfigConfig::accel_y_kp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("accel_y_kp", "double", 0, "kp y Gain Acceleration", "", &pid_reconfigConfig::accel_y_kp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.accel_y_ki = -400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.accel_y_ki = 400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.accel_y_ki = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("accel_y_ki", "double", 0, "ki y Gain Acceleration", "", &pid_reconfigConfig::accel_y_ki)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("accel_y_ki", "double", 0, "ki y Gain Acceleration", "", &pid_reconfigConfig::accel_y_ki)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.accel_y_kd = -400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.accel_y_kd = 400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.accel_y_kd = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("accel_y_kd", "double", 0, "kd y Gain Acceleration", "", &pid_reconfigConfig::accel_y_kd)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("accel_y_kd", "double", 0, "kd y Gain Acceleration", "", &pid_reconfigConfig::accel_y_kd)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.accel_y_sat = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.accel_y_sat = 110.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.accel_y_sat = 1.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("accel_y_sat", "double", 0, "Sway Force Saturation (N)", "", &pid_reconfigConfig::accel_y_sat)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("accel_y_sat", "double", 0, "Sway Force Saturation (N)", "", &pid_reconfigConfig::accel_y_sat)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.accel_z_kp = -400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.accel_z_kp = 400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.accel_z_kp = 1.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("accel_z_kp", "double", 0, "kp z Gain Acceleration", "", &pid_reconfigConfig::accel_z_kp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("accel_z_kp", "double", 0, "kp z Gain Acceleration", "", &pid_reconfigConfig::accel_z_kp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.accel_z_ki = -400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.accel_z_ki = 400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.accel_z_ki = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("accel_z_ki", "double", 0, "ki z Gain Acceleration", "", &pid_reconfigConfig::accel_z_ki)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("accel_z_ki", "double", 0, "ki z Gain Acceleration", "", &pid_reconfigConfig::accel_z_ki)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.accel_z_kd = -400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.accel_z_kd = 400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.accel_z_kd = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("accel_z_kd", "double", 0, "kd z Gain Acceleration", "", &pid_reconfigConfig::accel_z_kd)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("accel_z_kd", "double", 0, "kd z Gain Acceleration", "", &pid_reconfigConfig::accel_z_kd)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.accel_z_sat = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.accel_z_sat = 110.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.accel_z_sat = 1.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("accel_z_sat", "double", 0, "Heave Force Saturation (N)", "", &pid_reconfigConfig::accel_z_sat)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("accel_z_sat", "double", 0, "Heave Force Saturation (N)", "", &pid_reconfigConfig::accel_z_sat)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.accel_r_kp = -400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.accel_r_kp = 400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.accel_r_kp = 1.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("accel_r_kp", "double", 0, "kp r Gain Acceleration", "", &pid_reconfigConfig::accel_r_kp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("accel_r_kp", "double", 0, "kp r Gain Acceleration", "", &pid_reconfigConfig::accel_r_kp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.accel_r_ki = -400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.accel_r_ki = 400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.accel_r_ki = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("accel_r_ki", "double", 0, "ki r Gain Acceleration", "", &pid_reconfigConfig::accel_r_ki)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("accel_r_ki", "double", 0, "ki r Gain Acceleration", "", &pid_reconfigConfig::accel_r_ki)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.accel_r_kd = -400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.accel_r_kd = 400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.accel_r_kd = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("accel_r_kd", "double", 0, "kd r Gain Acceleration", "", &pid_reconfigConfig::accel_r_kd)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("accel_r_kd", "double", 0, "kd r Gain Acceleration", "", &pid_reconfigConfig::accel_r_kd)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.accel_r_sat = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.accel_r_sat = 40.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.accel_r_sat = 1.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("accel_r_sat", "double", 0, "Yaw Moment Saturation (N)", "", &pid_reconfigConfig::accel_r_sat)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("accel_r_sat", "double", 0, "Yaw Moment Saturation (N)", "", &pid_reconfigConfig::accel_r_sat)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.vel_x_kp = -400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.vel_x_kp = 400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.vel_x_kp = 1.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("vel_x_kp", "double", 0, "kp x Gain Velocity", "", &pid_reconfigConfig::vel_x_kp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("vel_x_kp", "double", 0, "kp x Gain Velocity", "", &pid_reconfigConfig::vel_x_kp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.vel_x_ki = -400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.vel_x_ki = 400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.vel_x_ki = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("vel_x_ki", "double", 0, "ki x Gain Velocity", "", &pid_reconfigConfig::vel_x_ki)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("vel_x_ki", "double", 0, "ki x Gain Velocity", "", &pid_reconfigConfig::vel_x_ki)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.vel_x_kd = -400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.vel_x_kd = 400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.vel_x_kd = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("vel_x_kd", "double", 0, "kd x Gain Velocity", "", &pid_reconfigConfig::vel_x_kd)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("vel_x_kd", "double", 0, "kd x Gain Velocity", "", &pid_reconfigConfig::vel_x_kd)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.vel_x_sat = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.vel_x_sat = 10.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.vel_x_sat = 1.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("vel_x_sat", "double", 0, "x Acceleration SP Limits", "", &pid_reconfigConfig::vel_x_sat)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("vel_x_sat", "double", 0, "x Acceleration SP Limits", "", &pid_reconfigConfig::vel_x_sat)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.vel_x_lim = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.vel_x_lim = 2.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.vel_x_lim = 1.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("vel_x_lim", "double", 0, "x Velocity SP limit (Overrides Position Controller)", "", &pid_reconfigConfig::vel_x_lim)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("vel_x_lim", "double", 0, "x Velocity SP limit (Overrides Position Controller)", "", &pid_reconfigConfig::vel_x_lim)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.vel_y_kp = -400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.vel_y_kp = 400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.vel_y_kp = 1.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("vel_y_kp", "double", 0, "kp y Gain Velocity", "", &pid_reconfigConfig::vel_y_kp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("vel_y_kp", "double", 0, "kp y Gain Velocity", "", &pid_reconfigConfig::vel_y_kp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.vel_y_ki = -400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.vel_y_ki = 400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.vel_y_ki = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("vel_y_ki", "double", 0, "ki y Gain Velocity", "", &pid_reconfigConfig::vel_y_ki)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("vel_y_ki", "double", 0, "ki y Gain Velocity", "", &pid_reconfigConfig::vel_y_ki)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.vel_y_kd = -400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.vel_y_kd = 400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.vel_y_kd = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("vel_y_kd", "double", 0, "kd y Gain Velocity", "", &pid_reconfigConfig::vel_y_kd)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("vel_y_kd", "double", 0, "kd y Gain Velocity", "", &pid_reconfigConfig::vel_y_kd)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.vel_y_sat = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.vel_y_sat = 10.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.vel_y_sat = 1.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("vel_y_sat", "double", 0, "y Acceleration SP Limits", "", &pid_reconfigConfig::vel_y_sat)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("vel_y_sat", "double", 0, "y Acceleration SP Limits", "", &pid_reconfigConfig::vel_y_sat)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.vel_y_lim = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.vel_y_lim = 2.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.vel_y_lim = 1.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("vel_y_lim", "double", 0, "y Velocity SP limit (Overrides Position Controller)", "", &pid_reconfigConfig::vel_y_lim)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("vel_y_lim", "double", 0, "y Velocity SP limit (Overrides Position Controller)", "", &pid_reconfigConfig::vel_y_lim)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.vel_z_kp = -400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.vel_z_kp = 400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.vel_z_kp = 1.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("vel_z_kp", "double", 0, "kp z Gain Velocity", "", &pid_reconfigConfig::vel_z_kp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("vel_z_kp", "double", 0, "kp z Gain Velocity", "", &pid_reconfigConfig::vel_z_kp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.vel_z_ki = -400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.vel_z_ki = 400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.vel_z_ki = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("vel_z_ki", "double", 0, "ki z Gain Velocity", "", &pid_reconfigConfig::vel_z_ki)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("vel_z_ki", "double", 0, "ki z Gain Velocity", "", &pid_reconfigConfig::vel_z_ki)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.vel_z_kd = -400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.vel_z_kd = 400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.vel_z_kd = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("vel_z_kd", "double", 0, "kd z Gain Velocity", "", &pid_reconfigConfig::vel_z_kd)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("vel_z_kd", "double", 0, "kd z Gain Velocity", "", &pid_reconfigConfig::vel_z_kd)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.vel_z_sat = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.vel_z_sat = 10.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.vel_z_sat = 1.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("vel_z_sat", "double", 0, "z Acceleration SP Limits", "", &pid_reconfigConfig::vel_z_sat)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("vel_z_sat", "double", 0, "z Acceleration SP Limits", "", &pid_reconfigConfig::vel_z_sat)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.vel_z_lim = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.vel_z_lim = 2.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.vel_z_lim = 1.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("vel_z_lim", "double", 0, "z Velocity SP limit (Overrides Position Controller)", "", &pid_reconfigConfig::vel_z_lim)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("vel_z_lim", "double", 0, "z Velocity SP limit (Overrides Position Controller)", "", &pid_reconfigConfig::vel_z_lim)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.vel_r_kp = -400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.vel_r_kp = 400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.vel_r_kp = 1.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("vel_r_kp", "double", 0, "kp r Gain Velocity", "", &pid_reconfigConfig::vel_r_kp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("vel_r_kp", "double", 0, "kp r Gain Velocity", "", &pid_reconfigConfig::vel_r_kp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.vel_r_ki = -400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.vel_r_ki = 400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.vel_r_ki = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("vel_r_ki", "double", 0, "ki r Gain Velocity", "", &pid_reconfigConfig::vel_r_ki)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("vel_r_ki", "double", 0, "ki r Gain Velocity", "", &pid_reconfigConfig::vel_r_ki)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.vel_r_kd = -400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.vel_r_kd = 400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.vel_r_kd = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("vel_r_kd", "double", 0, "kd r Gain Velocity", "", &pid_reconfigConfig::vel_r_kd)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("vel_r_kd", "double", 0, "kd r Gain Velocity", "", &pid_reconfigConfig::vel_r_kd)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.vel_r_sat = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.vel_r_sat = 10.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.vel_r_sat = 1.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("vel_r_sat", "double", 0, "r Acceleration SP Limits", "", &pid_reconfigConfig::vel_r_sat)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("vel_r_sat", "double", 0, "r Acceleration SP Limits", "", &pid_reconfigConfig::vel_r_sat)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.vel_r_lim = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.vel_r_lim = 0.5;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.vel_r_lim = 1.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("vel_r_lim", "double", 0, "r Velocity limit (Overrides Position Controller)", "", &pid_reconfigConfig::vel_r_lim)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("vel_r_lim", "double", 0, "r Velocity limit (Overrides Position Controller)", "", &pid_reconfigConfig::vel_r_lim)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pos_x_kp = -400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pos_x_kp = 400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pos_x_kp = 1.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("pos_x_kp", "double", 0, "kp x Gain Position", "", &pid_reconfigConfig::pos_x_kp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("pos_x_kp", "double", 0, "kp x Gain Position", "", &pid_reconfigConfig::pos_x_kp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pos_x_ki = -400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pos_x_ki = 400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pos_x_ki = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("pos_x_ki", "double", 0, "ki x Gain Position", "", &pid_reconfigConfig::pos_x_ki)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("pos_x_ki", "double", 0, "ki x Gain Position", "", &pid_reconfigConfig::pos_x_ki)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pos_x_kd = -400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pos_x_kd = 400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pos_x_kd = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("pos_x_kd", "double", 0, "kd x Gain Position", "", &pid_reconfigConfig::pos_x_kd)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("pos_x_kd", "double", 0, "kd x Gain Position", "", &pid_reconfigConfig::pos_x_kd)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pos_x_sat = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pos_x_sat = 2.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pos_x_sat = 1.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("pos_x_sat", "double", 0, "x Velocity SP Limits", "", &pid_reconfigConfig::pos_x_sat)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("pos_x_sat", "double", 0, "x Velocity SP Limits", "", &pid_reconfigConfig::pos_x_sat)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pos_y_kp = -400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pos_y_kp = 400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pos_y_kp = 1.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("pos_y_kp", "double", 0, "kp y Gain Position", "", &pid_reconfigConfig::pos_y_kp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("pos_y_kp", "double", 0, "kp y Gain Position", "", &pid_reconfigConfig::pos_y_kp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pos_y_ki = -400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pos_y_ki = 400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pos_y_ki = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("pos_y_ki", "double", 0, "ki y Gain Position", "", &pid_reconfigConfig::pos_y_ki)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("pos_y_ki", "double", 0, "ki y Gain Position", "", &pid_reconfigConfig::pos_y_ki)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pos_y_kd = -400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pos_y_kd = 400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pos_y_kd = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("pos_y_kd", "double", 0, "kd y Gain Position", "", &pid_reconfigConfig::pos_y_kd)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("pos_y_kd", "double", 0, "kd y Gain Position", "", &pid_reconfigConfig::pos_y_kd)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pos_y_sat = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pos_y_sat = 2.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pos_y_sat = 1.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("pos_y_sat", "double", 0, "y Velocity SP Limits", "", &pid_reconfigConfig::pos_y_sat)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("pos_y_sat", "double", 0, "y Velocity SP Limits", "", &pid_reconfigConfig::pos_y_sat)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pos_z_kp = -400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pos_z_kp = 400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pos_z_kp = 1.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("pos_z_kp", "double", 0, "kp z Gain Position", "", &pid_reconfigConfig::pos_z_kp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("pos_z_kp", "double", 0, "kp z Gain Position", "", &pid_reconfigConfig::pos_z_kp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pos_z_ki = -400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pos_z_ki = 400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pos_z_ki = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("pos_z_ki", "double", 0, "ki z Gain Position", "", &pid_reconfigConfig::pos_z_ki)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("pos_z_ki", "double", 0, "ki z Gain Position", "", &pid_reconfigConfig::pos_z_ki)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pos_z_kd = -400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pos_z_kd = 400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pos_z_kd = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("pos_z_kd", "double", 0, "kd z Gain Position", "", &pid_reconfigConfig::pos_z_kd)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("pos_z_kd", "double", 0, "kd z Gain Position", "", &pid_reconfigConfig::pos_z_kd)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pos_z_sat = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pos_z_sat = 2.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pos_z_sat = 1.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("pos_z_sat", "double", 0, "z Velocity SP Limits", "", &pid_reconfigConfig::pos_z_sat)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("pos_z_sat", "double", 0, "z Velocity SP Limits", "", &pid_reconfigConfig::pos_z_sat)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pos_r_kp = -400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pos_r_kp = 400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pos_r_kp = 1.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("pos_r_kp", "double", 0, "kp r Gain Position", "", &pid_reconfigConfig::pos_r_kp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("pos_r_kp", "double", 0, "kp r Gain Position", "", &pid_reconfigConfig::pos_r_kp)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pos_r_ki = -400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pos_r_ki = 400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pos_r_ki = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("pos_r_ki", "double", 0, "ki r Gain Position", "", &pid_reconfigConfig::pos_r_ki)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("pos_r_ki", "double", 0, "ki r Gain Position", "", &pid_reconfigConfig::pos_r_ki)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pos_r_kd = -400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pos_r_kd = 400.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pos_r_kd = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("pos_r_kd", "double", 0, "kd r Gain Position", "", &pid_reconfigConfig::pos_r_kd)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("pos_r_kd", "double", 0, "kd r Gain Position", "", &pid_reconfigConfig::pos_r_kd)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.pos_r_sat = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.pos_r_sat = 0.5;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.pos_r_sat = 1.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("pos_r_sat", "double", 0, "yaw Velocity SP Limits", "", &pid_reconfigConfig::pos_r_sat)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(pid_reconfigConfig::AbstractParamDescriptionConstPtr(new pid_reconfigConfig::ParamDescription<double>("pos_r_sat", "double", 0, "yaw Velocity SP Limits", "", &pid_reconfigConfig::pos_r_sat)));
//#line 247 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 247 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(pid_reconfigConfig::AbstractGroupDescriptionConstPtr(new pid_reconfigConfig::GroupDescription<pid_reconfigConfig::DEFAULT, pid_reconfigConfig>(Default)));
//#line 369 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<pid_reconfigConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<pid_reconfigConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<pid_reconfigConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    pid_reconfigConfig __max__;
    pid_reconfigConfig __min__;
    pid_reconfigConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const pid_reconfigConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static pid_reconfigConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &pid_reconfigConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const pid_reconfigConfig &pid_reconfigConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const pid_reconfigConfig &pid_reconfigConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const pid_reconfigConfig &pid_reconfigConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<pid_reconfigConfig::AbstractParamDescriptionConstPtr> &pid_reconfigConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<pid_reconfigConfig::AbstractGroupDescriptionConstPtr> &pid_reconfigConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const pid_reconfigConfigStatics *pid_reconfigConfig::__get_statics__()
  {
    const static pid_reconfigConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = pid_reconfigConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __PID_RECONFIGRECONFIGURATOR_H__
