// Generated by gencpp from file bluerov2_control/SetControlMode.msg
// DO NOT EDIT!


#ifndef BLUEROV2_CONTROL_MESSAGE_SETCONTROLMODE_H
#define BLUEROV2_CONTROL_MESSAGE_SETCONTROLMODE_H

#include <ros/service_traits.h>


#include <bluerov2_control/SetControlModeRequest.h>
#include <bluerov2_control/SetControlModeResponse.h>


namespace bluerov2_control
{

struct SetControlMode
{

typedef SetControlModeRequest Request;
typedef SetControlModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetControlMode
} // namespace bluerov2_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bluerov2_control::SetControlMode > {
  static const char* value()
  {
    return "2b04d4d97f408d2de1f22ad0896570fc";
  }

  static const char* value(const ::bluerov2_control::SetControlMode&) { return value(); }
};

template<>
struct DataType< ::bluerov2_control::SetControlMode > {
  static const char* value()
  {
    return "bluerov2_control/SetControlMode";
  }

  static const char* value(const ::bluerov2_control::SetControlMode&) { return value(); }
};


// service_traits::MD5Sum< ::bluerov2_control::SetControlModeRequest> should match
// service_traits::MD5Sum< ::bluerov2_control::SetControlMode >
template<>
struct MD5Sum< ::bluerov2_control::SetControlModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bluerov2_control::SetControlMode >::value();
  }
  static const char* value(const ::bluerov2_control::SetControlModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bluerov2_control::SetControlModeRequest> should match
// service_traits::DataType< ::bluerov2_control::SetControlMode >
template<>
struct DataType< ::bluerov2_control::SetControlModeRequest>
{
  static const char* value()
  {
    return DataType< ::bluerov2_control::SetControlMode >::value();
  }
  static const char* value(const ::bluerov2_control::SetControlModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bluerov2_control::SetControlModeResponse> should match
// service_traits::MD5Sum< ::bluerov2_control::SetControlMode >
template<>
struct MD5Sum< ::bluerov2_control::SetControlModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bluerov2_control::SetControlMode >::value();
  }
  static const char* value(const ::bluerov2_control::SetControlModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bluerov2_control::SetControlModeResponse> should match
// service_traits::DataType< ::bluerov2_control::SetControlMode >
template<>
struct DataType< ::bluerov2_control::SetControlModeResponse>
{
  static const char* value()
  {
    return DataType< ::bluerov2_control::SetControlMode >::value();
  }
  static const char* value(const ::bluerov2_control::SetControlModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BLUEROV2_CONTROL_MESSAGE_SETCONTROLMODE_H
