// Generated by gencpp from file bluerov2_control/SetControlModeRequest.msg
// DO NOT EDIT!


#ifndef BLUEROV2_CONTROL_MESSAGE_SETCONTROLMODEREQUEST_H
#define BLUEROV2_CONTROL_MESSAGE_SETCONTROLMODEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <bluerov2_control/ControlMode.h>

namespace bluerov2_control
{
template <class ContainerAllocator>
struct SetControlModeRequest_
{
  typedef SetControlModeRequest_<ContainerAllocator> Type;

  SetControlModeRequest_()
    : mode()  {
    }
  SetControlModeRequest_(const ContainerAllocator& _alloc)
    : mode(_alloc)  {
  (void)_alloc;
    }



   typedef  ::bluerov2_control::ControlMode_<ContainerAllocator>  _mode_type;
  _mode_type mode;





  typedef boost::shared_ptr< ::bluerov2_control::SetControlModeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bluerov2_control::SetControlModeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetControlModeRequest_

typedef ::bluerov2_control::SetControlModeRequest_<std::allocator<void> > SetControlModeRequest;

typedef boost::shared_ptr< ::bluerov2_control::SetControlModeRequest > SetControlModeRequestPtr;
typedef boost::shared_ptr< ::bluerov2_control::SetControlModeRequest const> SetControlModeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bluerov2_control::SetControlModeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bluerov2_control::SetControlModeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bluerov2_control::SetControlModeRequest_<ContainerAllocator1> & lhs, const ::bluerov2_control::SetControlModeRequest_<ContainerAllocator2> & rhs)
{
  return lhs.mode == rhs.mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bluerov2_control::SetControlModeRequest_<ContainerAllocator1> & lhs, const ::bluerov2_control::SetControlModeRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bluerov2_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::bluerov2_control::SetControlModeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bluerov2_control::SetControlModeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bluerov2_control::SetControlModeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bluerov2_control::SetControlModeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bluerov2_control::SetControlModeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bluerov2_control::SetControlModeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bluerov2_control::SetControlModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ccbf3c76b075baeeeac2d4c34686ba68";
  }

  static const char* value(const ::bluerov2_control::SetControlModeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xccbf3c76b075baeeULL;
  static const uint64_t static_value2 = 0xeac2d4c34686ba68ULL;
};

template<class ContainerAllocator>
struct DataType< ::bluerov2_control::SetControlModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bluerov2_control/SetControlModeRequest";
  }

  static const char* value(const ::bluerov2_control::SetControlModeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bluerov2_control::SetControlModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bluerov2_control/ControlMode mode\n"
"\n"
"================================================================================\n"
"MSG: bluerov2_control/ControlMode\n"
"uint8 OFF=0\n"
"uint8 IDLE=1\n"
"uint8 ACCELTELEOP=2\n"
"uint8 VELTELEOP=3\n"
"uint8 HOLDPOSITION=4\n"
"uint8 AUTOPILOT=5\n"
"uint8 LOSGUIDANCE=6\n"
"uint8 ABORT=7\n"
"\n"
"uint8 mode\n"
;
  }

  static const char* value(const ::bluerov2_control::SetControlModeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bluerov2_control::SetControlModeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetControlModeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bluerov2_control::SetControlModeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bluerov2_control::SetControlModeRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "mode: ";
    Printer< ::bluerov2_control::ControlMode_<ContainerAllocator> >::stream(s, indent + "  ", v.mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BLUEROV2_CONTROL_MESSAGE_SETCONTROLMODEREQUEST_H
