// Generated by gencpp from file bluerov2_dobmpc/Reference.msg
// DO NOT EDIT!


#ifndef BLUEROV2_DOBMPC_MESSAGE_REFERENCE_H
#define BLUEROV2_DOBMPC_MESSAGE_REFERENCE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Twist.h>

namespace bluerov2_dobmpc
{
template <class ContainerAllocator>
struct Reference_
{
  typedef Reference_<ContainerAllocator> Type;

  Reference_()
    : header()
    , ref_pose()
    , ref_twist()  {
    }
  Reference_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , ref_pose(_alloc)
    , ref_twist(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::geometry_msgs::Pose_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Pose_<ContainerAllocator> >> _ref_pose_type;
  _ref_pose_type ref_pose;

   typedef std::vector< ::geometry_msgs::Twist_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Twist_<ContainerAllocator> >> _ref_twist_type;
  _ref_twist_type ref_twist;





  typedef boost::shared_ptr< ::bluerov2_dobmpc::Reference_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bluerov2_dobmpc::Reference_<ContainerAllocator> const> ConstPtr;

}; // struct Reference_

typedef ::bluerov2_dobmpc::Reference_<std::allocator<void> > Reference;

typedef boost::shared_ptr< ::bluerov2_dobmpc::Reference > ReferencePtr;
typedef boost::shared_ptr< ::bluerov2_dobmpc::Reference const> ReferenceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bluerov2_dobmpc::Reference_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bluerov2_dobmpc::Reference_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bluerov2_dobmpc::Reference_<ContainerAllocator1> & lhs, const ::bluerov2_dobmpc::Reference_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.ref_pose == rhs.ref_pose &&
    lhs.ref_twist == rhs.ref_twist;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bluerov2_dobmpc::Reference_<ContainerAllocator1> & lhs, const ::bluerov2_dobmpc::Reference_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bluerov2_dobmpc

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::bluerov2_dobmpc::Reference_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bluerov2_dobmpc::Reference_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bluerov2_dobmpc::Reference_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bluerov2_dobmpc::Reference_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bluerov2_dobmpc::Reference_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bluerov2_dobmpc::Reference_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bluerov2_dobmpc::Reference_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a5a6b3393e50b440b27316a2d50af420";
  }

  static const char* value(const ::bluerov2_dobmpc::Reference_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa5a6b3393e50b440ULL;
  static const uint64_t static_value2 = 0xb27316a2d50af420ULL;
};

template<class ContainerAllocator>
struct DataType< ::bluerov2_dobmpc::Reference_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bluerov2_dobmpc/Reference";
  }

  static const char* value(const ::bluerov2_dobmpc::Reference_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bluerov2_dobmpc::Reference_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"geometry_msgs/Pose[] ref_pose\n"
"geometry_msgs/Twist[] ref_twist\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3 linear\n"
"Vector3 angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::bluerov2_dobmpc::Reference_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bluerov2_dobmpc::Reference_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.ref_pose);
      stream.next(m.ref_twist);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Reference_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bluerov2_dobmpc::Reference_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bluerov2_dobmpc::Reference_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ref_pose: ";
    if (v.ref_pose.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.ref_pose.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.ref_pose[i]);
    }
    if (v.ref_pose.empty() || false)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ref_twist: ";
    if (v.ref_twist.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.ref_twist.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::geometry_msgs::Twist_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.ref_twist[i]);
    }
    if (v.ref_twist.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // BLUEROV2_DOBMPC_MESSAGE_REFERENCE_H
