// Auto-generated. Do not edit!

// (in-package bluerov2_control.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class FollowWaypointsResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.waypoints_completed = null;
    }
    else {
      if (initObj.hasOwnProperty('waypoints_completed')) {
        this.waypoints_completed = initObj.waypoints_completed
      }
      else {
        this.waypoints_completed = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type FollowWaypointsResult
    // Serialize message field [waypoints_completed]
    bufferOffset = _serializer.uint32(obj.waypoints_completed, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type FollowWaypointsResult
    let len;
    let data = new FollowWaypointsResult(null);
    // Deserialize message field [waypoints_completed]
    data.waypoints_completed = _deserializer.uint32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'bluerov2_control/FollowWaypointsResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '3a91b58e3838e0eae5c75dc8d25cfb82';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define the result
    uint32 waypoints_completed
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new FollowWaypointsResult(null);
    if (msg.waypoints_completed !== undefined) {
      resolved.waypoints_completed = msg.waypoints_completed;
    }
    else {
      resolved.waypoints_completed = 0
    }

    return resolved;
    }
};

module.exports = FollowWaypointsResult;
