// Auto-generated. Do not edit!

// (in-package bluerov2_control.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class FollowWaypointsFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.percentage_complete = null;
    }
    else {
      if (initObj.hasOwnProperty('percentage_complete')) {
        this.percentage_complete = initObj.percentage_complete
      }
      else {
        this.percentage_complete = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type FollowWaypointsFeedback
    // Serialize message field [percentage_complete]
    bufferOffset = _serializer.float32(obj.percentage_complete, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type FollowWaypointsFeedback
    let len;
    let data = new FollowWaypointsFeedback(null);
    // Deserialize message field [percentage_complete]
    data.percentage_complete = _deserializer.float32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'bluerov2_control/FollowWaypointsFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'e59a2842413d60206f458c042f7cfd36';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define a feedback message
    float32 percentage_complete
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new FollowWaypointsFeedback(null);
    if (msg.percentage_complete !== undefined) {
      resolved.percentage_complete = msg.percentage_complete;
    }
    else {
      resolved.percentage_complete = 0.0
    }

    return resolved;
    }
};

module.exports = FollowWaypointsFeedback;
