/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) bluerov2_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {12, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {6, 1, 1};
static const casadi_int casadi_s3[3] = {16, 1, 1};

/* bluerov2_expl_vde_adj:(i0[12],i1[12],i2[4],i3[6])->(o0[16]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40;
  a00=0.;
  if (res[0]!=0) res[0][0]=a00;
  if (res[0]!=0) res[0][1]=a00;
  if (res[0]!=0) res[0][2]=a00;
  a00=arg[0]? arg[0][3] : 0;
  a01=cos(a00);
  a02=6.6000000000000003e-01;
  a03=arg[0]? arg[0][4] : 0;
  a04=cos(a03);
  a05=(a02*a04);
  a06=9.0163602939496948e-02;
  a07=arg[1]? arg[1][7] : 0;
  a06=(a06*a07);
  a07=(a05*a06);
  a07=(a01*a07);
  a08=2.2092120000000004e+00;
  a09=(a08*a04);
  a10=3.3841405636624526e+00;
  a11=arg[1]? arg[1][9] : 0;
  a10=(a10*a11);
  a09=(a09*a10);
  a09=(a01*a09);
  a00=sin(a00);
  a11=5.9780009564801527e-02;
  a12=arg[1]? arg[1][8] : 0;
  a11=(a11*a12);
  a05=(a05*a11);
  a05=(a00*a05);
  a09=(a09+a05);
  a07=(a07-a09);
  a09=arg[0]? arg[0][11] : 0;
  a05=arg[1]? arg[1][5] : 0;
  a12=(a09*a05);
  a13=(a12/a04);
  a13=(a00*a13);
  a07=(a07-a13);
  a13=arg[0]? arg[0][10] : 0;
  a14=(a13*a05);
  a15=(a14/a04);
  a15=(a01*a15);
  a07=(a07+a15);
  a15=arg[1]? arg[1][4] : 0;
  a16=(a09*a15);
  a16=(a01*a16);
  a07=(a07+a16);
  a16=(a13*a15);
  a16=(a00*a16);
  a07=(a07-a16);
  a03=sin(a03);
  a16=arg[1]? arg[1][3] : 0;
  a17=(a09*a16);
  a18=(a17/a04);
  a19=(a03*a18);
  a19=(a00*a19);
  a07=(a07-a19);
  a19=arg[0]? arg[0][8] : 0;
  a20=arg[1]? arg[1][2] : 0;
  a21=(a19*a20);
  a22=(a04*a21);
  a22=(a00*a22);
  a07=(a07-a22);
  a22=arg[0]? arg[0][7] : 0;
  a23=(a22*a20);
  a24=(a04*a23);
  a24=(a01*a24);
  a07=(a07+a24);
  a24=arg[0]? arg[0][5] : 0;
  a25=cos(a24);
  a26=arg[1]? arg[1][1] : 0;
  a27=(a19*a26);
  a28=(a25*a27);
  a28=(a01*a28);
  a07=(a07-a28);
  a24=sin(a24);
  a28=(a03*a24);
  a29=(a28*a27);
  a29=(a00*a29);
  a07=(a07-a29);
  a29=(a22*a26);
  a30=(a24*a29);
  a31=(a03*a30);
  a31=(a01*a31);
  a07=(a07+a31);
  a31=(a25*a29);
  a31=(a00*a31);
  a07=(a07-a31);
  a31=arg[1]? arg[1][0] : 0;
  a32=(a19*a31);
  a33=(a03*a32);
  a34=(a25*a33);
  a34=(a00*a34);
  a07=(a07-a34);
  a34=(a24*a32);
  a34=(a01*a34);
  a07=(a07+a34);
  a34=(a22*a31);
  a35=(a24*a34);
  a35=(a00*a35);
  a07=(a07+a35);
  a35=(a25*a03);
  a36=(a35*a34);
  a36=(a01*a36);
  a07=(a07+a36);
  if (res[0]!=0) res[0][3]=a07;
  a07=(a00*a10);
  a07=(a08*a07);
  a07=(a03*a07);
  a36=5.3356318092685262e-01;
  a37=arg[1]? arg[1][10] : 0;
  a36=(a36*a37);
  a08=(a08*a36);
  a08=(a04*a08);
  a07=(a07-a08);
  a08=(a01*a11);
  a08=(a02*a08);
  a08=(a03*a08);
  a07=(a07-a08);
  a08=(a00*a06);
  a08=(a02*a08);
  a08=(a03*a08);
  a07=(a07-a08);
  a08=7.7212942480368779e-02;
  a37=arg[1]? arg[1][6] : 0;
  a08=(a08*a37);
  a02=(a02*a08);
  a02=(a04*a02);
  a07=(a07-a02);
  a02=(a01/a04);
  a37=(a02/a04);
  a37=(a37*a12);
  a37=(a03*a37);
  a07=(a07+a37);
  a37=(a00/a04);
  a12=(a37/a04);
  a12=(a12*a14);
  a12=(a03*a12);
  a07=(a07+a12);
  a12=(a01*a03);
  a12=(a12/a04);
  a14=(a12/a04);
  a14=(a14*a17);
  a14=(a03*a14);
  a07=(a07+a14);
  a18=(a01*a18);
  a18=(a04*a18);
  a07=(a07+a18);
  a18=(a24*a03);
  a18=(a18/a04);
  a14=(a18/a04);
  a17=(a13*a16);
  a14=(a14*a17);
  a14=(a03*a14);
  a07=(a07+a14);
  a17=(a17/a04);
  a14=(a24*a17);
  a14=(a04*a14);
  a07=(a07+a14);
  a21=(a01*a21);
  a21=(a03*a21);
  a07=(a07-a21);
  a21=arg[0]? arg[0][6] : 0;
  a14=(a21*a20);
  a14=(a04*a14);
  a07=(a07-a14);
  a23=(a00*a23);
  a23=(a03*a23);
  a07=(a07-a23);
  a23=(a01*a27);
  a14=(a24*a23);
  a14=(a04*a14);
  a07=(a07+a14);
  a30=(a00*a30);
  a30=(a04*a30);
  a07=(a07+a30);
  a30=(a21*a26);
  a14=(a24*a30);
  a14=(a03*a14);
  a07=(a07-a14);
  a14=(a25*a01);
  a38=(a14*a32);
  a38=(a04*a38);
  a07=(a07+a38);
  a38=(a00*a34);
  a39=(a25*a38);
  a39=(a04*a39);
  a07=(a07+a39);
  a39=(a21*a31);
  a40=(a25*a39);
  a40=(a03*a40);
  a07=(a07-a40);
  if (res[0]!=0) res[0][4]=a07;
  a17=(a03*a17);
  a17=(a25*a17);
  a27=(a00*a27);
  a27=(a24*a27);
  a17=(a17+a27);
  a23=(a03*a23);
  a23=(a25*a23);
  a17=(a17+a23);
  a23=(a00*a03);
  a27=(a23*a29);
  a27=(a25*a27);
  a17=(a17+a27);
  a29=(a01*a29);
  a29=(a24*a29);
  a17=(a17-a29);
  a30=(a04*a30);
  a30=(a25*a30);
  a17=(a17+a30);
  a33=(a01*a33);
  a33=(a24*a33);
  a17=(a17-a33);
  a32=(a00*a32);
  a32=(a25*a32);
  a17=(a17+a32);
  a34=(a01*a34);
  a34=(a25*a34);
  a17=(a17-a34);
  a38=(a03*a38);
  a38=(a24*a38);
  a17=(a17-a38);
  a39=(a04*a39);
  a39=(a24*a39);
  a17=(a17-a39);
  if (res[0]!=0) res[0][5]=a17;
  a17=1.1260000000000000e+01;
  a39=(a17*a13);
  a38=(a39*a11);
  a34=(a17*a09);
  a32=(a34*a06);
  a38=(a38-a32);
  a32=(a03*a20);
  a38=(a38-a32);
  a32=(a24*a04);
  a32=(a32*a26);
  a38=(a38+a32);
  a32=(a25*a04);
  a32=(a32*a31);
  a38=(a38+a32);
  if (res[0]!=0) res[0][6]=a38;
  a34=(a34*a08);
  a38=arg[0]? arg[0][9] : 0;
  a32=(a17*a38);
  a33=(a32*a11);
  a34=(a34-a33);
  a33=(a04*a00);
  a33=(a33*a20);
  a34=(a34+a33);
  a23=(a23*a24);
  a23=(a14+a23);
  a23=(a23*a26);
  a34=(a34+a23);
  a35=(a35*a00);
  a23=(a24*a01);
  a35=(a35-a23);
  a35=(a35*a31);
  a34=(a34+a35);
  if (res[0]!=0) res[0][7]=a34;
  a32=(a32*a06);
  a39=(a39*a08);
  a32=(a32-a39);
  a04=(a04*a01);
  a04=(a04*a20);
  a32=(a32+a04);
  a28=(a28*a01);
  a25=(a25*a00);
  a28=(a28-a25);
  a28=(a28*a26);
  a32=(a32+a28);
  a24=(a24*a00);
  a14=(a14*a03);
  a24=(a24+a14);
  a24=(a24*a31);
  a32=(a32+a24);
  if (res[0]!=0) res[0][8]=a32;
  a32=2.7999999999999997e-01;
  a24=(a09*a36);
  a24=(a32*a24);
  a31=3.3000000000000002e-01;
  a14=1.0197838058331634e+00;
  a03=arg[1]? arg[1][11] : 0;
  a14=(a14*a03);
  a03=(a13*a14);
  a03=(a31*a03);
  a24=(a24-a03);
  a03=(a22*a11);
  a03=(a17*a03);
  a24=(a24-a03);
  a03=(a19*a06);
  a03=(a17*a03);
  a24=(a24+a03);
  a24=(a24+a16);
  if (res[0]!=0) res[0][9]=a24;
  a24=5.0000000000000044e-02;
  a09=(a09*a10);
  a09=(a24*a09);
  a31=(a31*a38);
  a31=(a31*a14);
  a09=(a09-a31);
  a31=(a21*a11);
  a31=(a17*a31);
  a09=(a09+a31);
  a19=(a19*a08);
  a19=(a17*a19);
  a09=(a09-a19);
  a37=(a37*a05);
  a09=(a09+a37);
  a01=(a01*a15);
  a09=(a09+a01);
  a18=(a18*a16);
  a09=(a09+a18);
  if (res[0]!=0) res[0][10]=a09;
  a32=(a32*a38);
  a32=(a32*a36);
  a24=(a24*a13);
  a24=(a24*a10);
  a32=(a32+a24);
  a21=(a21*a06);
  a21=(a17*a21);
  a32=(a32-a21);
  a22=(a22*a08);
  a17=(a17*a22);
  a32=(a32+a17);
  a02=(a02*a05);
  a32=(a32+a02);
  a00=(a00*a15);
  a32=(a32+a00);
  a12=(a12*a16);
  a32=(a32+a12);
  if (res[0]!=0) res[0][11]=a32;
  a32=3.7669095518205658e+01;
  a12=1.7500892834341344e-01;
  a12=(a12*a14);
  a16=5.1265241636417137e-02;
  a16=(a16*a36);
  a12=(a12+a16);
  a16=-5.1265241635632258e-02;
  a16=(a16*a10);
  a12=(a12+a16);
  a16=-7.0710678118113479e-01;
  a16=(a16*a06);
  a12=(a12+a16);
  a16=-7.0710678119196069e-01;
  a16=(a16*a08);
  a12=(a12+a16);
  a12=(a32*a12);
  a00=-1.7500892834341342e-01;
  a00=(a00*a14);
  a15=5.1265241636417144e-02;
  a15=(a15*a36);
  a00=(a00+a15);
  a15=5.1265241635632272e-02;
  a15=(a15*a10);
  a00=(a00+a15);
  a15=7.0710678118113479e-01;
  a15=(a15*a06);
  a00=(a00+a15);
  a00=(a00+a16);
  a00=(a32*a00);
  a16=(a12+a00);
  a15=-1.6652364696949601e-01;
  a15=(a15*a14);
  a02=-5.1265241635893875e-02;
  a02=(a02*a36);
  a15=(a15+a02);
  a02=-5.1265241636155506e-02;
  a02=(a02*a10);
  a15=(a15+a02);
  a02=-7.0710678118835191e-01;
  a02=(a02*a06);
  a15=(a15+a02);
  a02=7.0710678118474313e-01;
  a02=(a02*a08);
  a15=(a15+a02);
  a15=(a32*a15);
  a16=(a16-a15);
  a08=1.6652364696949601e-01;
  a08=(a08*a14);
  a14=-5.1265241635893882e-02;
  a14=(a14*a36);
  a08=(a08+a14);
  a14=5.1265241636155520e-02;
  a14=(a14*a10);
  a08=(a08+a14);
  a14=7.0710678118835191e-01;
  a14=(a14*a06);
  a08=(a08+a14);
  a08=(a08+a02);
  a08=(a32*a08);
  a16=(a16-a08);
  if (res[0]!=0) res[0][12]=a16;
  a16=(a00-a12);
  a16=(a16-a15);
  a16=(a16+a08);
  if (res[0]!=0) res[0][13]=a16;
  a16=1.2000000000002554e-01;
  a16=(a16*a36);
  a02=2.1805000000000005e-01;
  a02=(a02*a10);
  a14=(a16+a02);
  a06=1.0000000000000002e+00;
  a06=(a06*a11);
  a14=(a14+a06);
  a14=(a32*a14);
  a11=-1.1999999999997452e-01;
  a11=(a11*a36);
  a11=(a11+a02);
  a11=(a11+a06);
  a11=(a32*a11);
  a14=(a14+a11);
  a11=-2.1805000000000005e-01;
  a11=(a11*a10);
  a16=(a16+a11);
  a16=(a16+a06);
  a16=(a32*a16);
  a14=(a14+a16);
  a16=-1.1999999999997450e-01;
  a16=(a16*a36);
  a16=(a16+a11);
  a16=(a16+a06);
  a32=(a32*a16);
  a14=(a14+a32);
  a14=(-a14);
  if (res[0]!=0) res[0][14]=a14;
  a12=(a12-a00);
  a12=(a12-a15);
  a12=(a12+a08);
  if (res[0]!=0) res[0][15]=a12;
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov2_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int bluerov2_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov2_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bluerov2_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int bluerov2_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bluerov2_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void bluerov2_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void bluerov2_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int bluerov2_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int bluerov2_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real bluerov2_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bluerov2_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bluerov2_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bluerov2_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bluerov2_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int bluerov2_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov2_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
