(cl:defpackage bluerov2_control-msg
  (:use )
  (:export
   "<AUTOPILOT>"
   "AUTOPILOT"
   "<CONTROLMODE>"
   "CONTROLMODE"
   "<FOLLOWWAYPOINTSACTION>"
   "FOLLOWWAYPOINTSACTION"
   "<FOLLOWWAYPOINTSACTIONFEEDBACK>"
   "FOLLOWWAYPOINTSACTIONFEEDBACK"
   "<FOLLOWWAYPOINTSACTIONGOAL>"
   "FOLLOWWAYPOINTSACTIONGOAL"
   "<FOLLOWWAYPOINTSACTIONRESULT>"
   "FOLLOWWAYPOINTSACTIONRESULT"
   "<FOLLOWWAYPOINTSFEEDBACK>"
   "FOLLOWWAYPOINTSFEEDBACK"
   "<FOLLOWWAYPOINTSGOAL>"
   "FOLLOWWAYPOINTSGOAL"
   "<FOLLOWWAYPOINTSRESULT>"
   "FOLLOWWAYPOINTSRESULT"
  ))

