; Auto-generated. Do not edit!


(cl:in-package bluerov2_control-msg)


;//! \htmlinclude FollowWaypointsResult.msg.html

(cl:defclass <FollowWaypointsResult> (roslisp-msg-protocol:ros-message)
  ((waypoints_completed
    :reader waypoints_completed
    :initarg :waypoints_completed
    :type cl:integer
    :initform 0))
)

(cl:defclass FollowWaypointsResult (<FollowWaypointsResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <FollowWaypointsResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'FollowWaypointsResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name bluerov2_control-msg:<FollowWaypointsResult> is deprecated: use bluerov2_control-msg:FollowWaypointsResult instead.")))

(cl:ensure-generic-function 'waypoints_completed-val :lambda-list '(m))
(cl:defmethod waypoints_completed-val ((m <FollowWaypointsResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader bluerov2_control-msg:waypoints_completed-val is deprecated.  Use bluerov2_control-msg:waypoints_completed instead.")
  (waypoints_completed m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <FollowWaypointsResult>) ostream)
  "Serializes a message object of type '<FollowWaypointsResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'waypoints_completed)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'waypoints_completed)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'waypoints_completed)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'waypoints_completed)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <FollowWaypointsResult>) istream)
  "Deserializes a message object of type '<FollowWaypointsResult>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'waypoints_completed)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'waypoints_completed)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'waypoints_completed)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'waypoints_completed)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<FollowWaypointsResult>)))
  "Returns string type for a message object of type '<FollowWaypointsResult>"
  "bluerov2_control/FollowWaypointsResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'FollowWaypointsResult)))
  "Returns string type for a message object of type 'FollowWaypointsResult"
  "bluerov2_control/FollowWaypointsResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<FollowWaypointsResult>)))
  "Returns md5sum for a message object of type '<FollowWaypointsResult>"
  "3a91b58e3838e0eae5c75dc8d25cfb82")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'FollowWaypointsResult)))
  "Returns md5sum for a message object of type 'FollowWaypointsResult"
  "3a91b58e3838e0eae5c75dc8d25cfb82")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<FollowWaypointsResult>)))
  "Returns full string definition for message of type '<FollowWaypointsResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%uint32 waypoints_completed~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'FollowWaypointsResult)))
  "Returns full string definition for message of type 'FollowWaypointsResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%uint32 waypoints_completed~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <FollowWaypointsResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <FollowWaypointsResult>))
  "Converts a ROS message object to a list"
  (cl:list 'FollowWaypointsResult
    (cl:cons ':waypoints_completed (waypoints_completed msg))
))
