; Auto-generated. Do not edit!


(cl:in-package bluerov2_control-msg)


;//! \htmlinclude FollowWaypointsFeedback.msg.html

(cl:defclass <FollowWaypointsFeedback> (roslisp-msg-protocol:ros-message)
  ((percentage_complete
    :reader percentage_complete
    :initarg :percentage_complete
    :type cl:float
    :initform 0.0))
)

(cl:defclass FollowWaypointsFeedback (<FollowWaypointsFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <FollowWaypointsFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'FollowWaypointsFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name bluerov2_control-msg:<FollowWaypointsFeedback> is deprecated: use bluerov2_control-msg:FollowWaypointsFeedback instead.")))

(cl:ensure-generic-function 'percentage_complete-val :lambda-list '(m))
(cl:defmethod percentage_complete-val ((m <FollowWaypointsFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader bluerov2_control-msg:percentage_complete-val is deprecated.  Use bluerov2_control-msg:percentage_complete instead.")
  (percentage_complete m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <FollowWaypointsFeedback>) ostream)
  "Serializes a message object of type '<FollowWaypointsFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'percentage_complete))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <FollowWaypointsFeedback>) istream)
  "Deserializes a message object of type '<FollowWaypointsFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'percentage_complete) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<FollowWaypointsFeedback>)))
  "Returns string type for a message object of type '<FollowWaypointsFeedback>"
  "bluerov2_control/FollowWaypointsFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'FollowWaypointsFeedback)))
  "Returns string type for a message object of type 'FollowWaypointsFeedback"
  "bluerov2_control/FollowWaypointsFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<FollowWaypointsFeedback>)))
  "Returns md5sum for a message object of type '<FollowWaypointsFeedback>"
  "e59a2842413d60206f458c042f7cfd36")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'FollowWaypointsFeedback)))
  "Returns md5sum for a message object of type 'FollowWaypointsFeedback"
  "e59a2842413d60206f458c042f7cfd36")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<FollowWaypointsFeedback>)))
  "Returns full string definition for message of type '<FollowWaypointsFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%float32 percentage_complete~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'FollowWaypointsFeedback)))
  "Returns full string definition for message of type 'FollowWaypointsFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%float32 percentage_complete~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <FollowWaypointsFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <FollowWaypointsFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'FollowWaypointsFeedback
    (cl:cons ':percentage_complete (percentage_complete msg))
))
